[tool.poetry]
name = "renewal_reminder"
version = "0.1.0"
description = ""
authors = ["Ben Roberts"]

[tool.poetry.dependencies]
python = "^3.7"
python-telegram-bot = "^11.1"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
pytest-clarity = {version = "^0.1.0-alpha.1",allows-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
