version: '3.3'

services:
  base:
    build:
      context: .
      dockerfile: base/Dockerfile
  mock_telegram_api:
    build:
      context: .
      dockerfile: mock_telegram_bot/Dockerfile
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
          - base